// TechGuide — catalog-img.js  [v1.63]
// RUTAS, no base64. Antes este archivo pesaba 904 KB porque traia las 82
// fotos embebidas como data-URI: el telefono bajaba TODAS aunque el asesor
// solo viera ocho. Ahora son archivos WebP sueltos en img/ (320 KB en total,
// 3.9 KB cada una) y el navegador baja unicamente las que se pintan.
// El contrato no cambia: IMG[id] sigue siendo una cadena que va directo a
// un src, asi que los consumidores de app.js, index.html y catalogo.html
// siguen funcionando sin tocarse.
window.IMG = {
  "ip18promax_512":"img/ip18promax.webp",
  "ip18promax":"img/ip18promax.webp",
  "ip18pro_512":"img/ip18pro.webp",
  "ip18pro":"img/ip18pro.webp",
  "h400":"img/h400.webp",
  "h400bal":"img/h400bal.webp",
  "hmagic7px8c":"img/hmagic7px8c.webp",
  "hmagic8lite":"img/hmagic8lite.webp",
  "hmagic8litejersey":"img/hmagic8litejersey.webp",
  "hmagic8pro":"img/hmagic8pro.webp",
  "honor600":"img/honor600.webp",
  "hx5c":"img/hx5c.webp",
  "hx5d":"img/hx5d.webp",
  "hx6c":"img/hx6c.webp",
  "hx7d":"img/hx7d.webp",
  "hx8d":"img/hx8d.webp",
  "ip15":"img/ip15.webp",
  "ip16":"img/ip16.webp",
  "ip16promax":"img/ip16promax.webp",
  "ip17":"img/ip17.webp",
  "ip17_512":"img/ip17_512.webp",
  "ip17e":"img/ip17e.webp",
  "ip17pro":"img/ip17pro.webp",
  "ip17pro_512":"img/ip17pro_512.webp",
  "ip17promax":"img/ip17promax.webp",
  "ip17promax_512":"img/ip17promax_512.webp",
  "medge60f":"img/medge60f.webp",
  "medge60pro":"img/medge60pro.webp",
  "medge60pro_w":"img/medge60pro_w.webp",
  "medge70":"img/medge70.webp",
  "medge70f_npi":"img/medge70f_npi.webp",
  "medge70pro_w":"img/medge70pro_w.webp",
  "medge70pro_wc":"img/medge70pro_wc.webp",
  "mg06":"img/mg06.webp",
  "mg17":"img/mg17.webp",
  "mg56":"img/mg56.webp",
  "mg77":"img/mg77.webp",
  "mrazr60u":"img/mrazr60u.webp",
  "opa5":"img/opa5.webp",
  "opa58":"img/opa58.webp",
  "opa5pro4g":"img/opa5pro4g.webp",
  "opa5pro5g":"img/opa5pro5g.webp",
  "opa6":"img/opa6.webp",
  "opa6k":"img/opa6k.webp",
  "opa6t":"img/opa6t.webp",
  "opa6x":"img/opa6x.webp",
  "opfindx9pro":"img/opfindx9pro.webp",
  "opreno13":"img/opreno13.webp",
  "opreno14":"img/opreno14.webp",
  "opreno14f":"img/opreno14f.webp",
  "opreno16f":"img/opreno16f.webp",
  "px10":"img/px10.webp",
  "px10_256":"img/px10_256.webp",
  "px10pro":"img/px10pro.webp",
  "px10pro_512":"img/px10pro_512.webp",
  "px10proxl":"img/px10proxl.webp",
  "px10proxl_512":"img/px10proxl_512.webp",
  "sa07":"img/sa07.webp",
  "sa07_128":"img/sa07_128.webp",
  "sa17":"img/sa17.webp",
  "sa27":"img/sa27.webp",
  "sa37":"img/sa37.webp",
  "sa57":"img/sa57.webp",
  "ss25u":"img/ss25u.webp",
  "ss26":"img/ss26.webp",
  "ss26plus":"img/ss26plus.webp",
  "ss26ultra":"img/ss26ultra.webp",
  "ss_zflip7":"img/ss_zflip7.webp",
  "ss_zflip8":"img/ss_zflip8.webp",
  "ss_zfold7":"img/ss_zfold7.webp",
  "ss_zfold8":"img/ss_zfold8.webp",
  "ss_zfold8u":"img/ss_zfold8u.webp",
  "x15t":"img/x15t.webp",
  "x15tpro":"img/x15tpro.webp",
  "x17t":"img/x17t.webp",
  "x17tpro":"img/x17tpro.webp",
  "x17ultra":"img/x17ultra.webp",
  "xr15":"img/xr15.webp",
  "xr15c":"img/xr15c.webp",
  "xr17":"img/xr17.webp",
  "xra5":"img/xra5.webp",
  "xra7pro":"img/xra7pro.webp",
  "xra7promochila":"img/xra7promochila.webp",
  "xrn15":"img/xrn15.webp",
  "xrn15pro":"img/xrn15pro.webp",
  "xrn17sp":"img/xrn17sp.webp"
};

// [v1.63.1] AVISO DE QUE YA ESTAN LISTAS.
// El catalog-img.js original terminaba con esta llamada y al regenerarlo la
// perdi. Sin ella nadie repinta: initMomento() y renderFlashCard() corren ANTES
// de que este archivo cargue, se encuentran IMG vacio y dejan el icono gris
// para siempre. index.html la usa para refrescar las vistas visibles.
try{ if(typeof window._onCatalogImgReady === 'function') window._onCatalogImgReady(); }catch(e){}
